service: sandwich-example

custom:       
  webpack:
    includeModules: false
    packager: 'yarn'

provider:
  name: aws
  runtime: nodejs12.x
  region: us-west-2 
  package:
    individually: true

functions:
  hello:
    handler: lambdas/ordered/handler.default
    timeout: 10
    sandwich:
      before: 
        handler: lambdas/ordered/before.default
      after: 
        handler: lambdas/ordered/after.default
        wrap: true
        

  protected:
    handler: lambdas/wrapped/handler.default
    timeout: 30
    sandwich:
      before: 
        handler: lambdas/wrapped/authenticate.default
        wrap: true
      after: 
        handler: lambdas/wrapped/apiResponse.default
        pipe: true

plugins:
  - serverless-plugin-sandwich
  - serverless-webpack