service: sandwich-example-node

plugins:
  - serverless-plugin-sandwich
 
package:
  individually: true

provider:
  name: aws
  runtime: nodejs12.x

functions:
  hello:
    handler: lambdas/ordered/handler.default
    timeout: 10
    sandwich:
      before: lambdas/ordered/before.default
      after: 
        handler: lambdas/ordered/after.default
        pipe: true

  protected:
    handler: lambdas/wrapped/handler.default
    timeout: 30
    sandwich:
      before: 
        handler: lambdas/wrapped/authenticate.default
        wrap: true
      after: 
        handler: lambdas/wrapped/apiResponse.default
        pipe: true
